server:
  port: 9000

spring:
  application:
    name: "users"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: "jdbc:mysql://localhost:3306/users-db"
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

eureka:
  instance:
    prefer-ip-address: true   # dla komunikacji między sobą serwisy będą korzystać z adresów ip zamiast hostów
  client:
    fetchRegistry: true   # serwis regularnie pobiera informacje o zarejestrowanych w Eurece serwisach
    register-with-eureka: true  # rejestruje się w Eurece po uruchomieniu
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    healthcheck:
      enabled: true   # regularne sprawdzenie zdrowia klienta przez Eureke (status "UP")

info:
  app:
    name: "users-ms"
    description: "Stock Exchange Users Application"
    version: "1.0.0"

management:
  health:
    readiness-state:
      enabled: true   # actuator/health/readiness stan gotownosci (wszystko zainicjowane)
    liveness-state:
      enabled: true   # actuator/health/liveness stan zycia (czy nadal dzila poprawnie)
  endpoints:
    web:
      exposure:
        include: "*"  # dostep do wszystkich endpointow actuatora z zewnatrz
  endpoint:
    shutdown:
      enabled: true   # actuator/shutdown wylaczenie z endpointa
    health:
      probes:
        enabled: true # dynamiczne monitorowanie i raportowanie stanu zdrowia aplikacji
  info:
    env:
      enabled: true   # actuator/info dostep do zmiennych srodowiskowych

# Properties które można załadować do zmiennych przy użyciu @ConfigurationProperties
users:
  message: "Welcome to Stock Exchange"
  contactDetails:
    name: "Mykola Nykolaichuk - programmer"
    email: "150174@stud.prz.edu.pl"
  onCallSupport:
    - +48 791-863-388
    - +38 098-517-95-96