server:
  port: 8070

spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071/"

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false   # serwis nie pobiera informacje o zarejestrowanych w Eurece serwisach
    register-with-eureka: false   #  nie rejestruje sie w Eurece jako klient po uruchomieniu
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  # dostep do wszystkich endpointow actuatora z zewnatrz

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
